### ISSUE TITLE
How do I enable it for .scss (sass) files?

### ISSUE THREAD

**Issue by zigi05** [SublimeText/TailwindCSS#4]
By doing "Open all with current extension as... > Tailwind CSS" doesn't work for nested classes.

**Comment by deathaxe** [comment]
As the name says this package provides CSS syntax. It extends ST's default CSS syntax package.

Supporting SCSS/SASS in the same way would require ST to provide those base syntaxes, too.

Extending any other 3rd-party package is not possible, because there is no way for a package to declare another one as dependency.
